<?php


$sLangName = "Russian";

$aLang = array(
'charset'							=> 'UTF-8', 	//UTF-8
'SHOP_THEME_GROUP_images'					=> 'Изображения', 	//Images
'SHOP_THEME_GROUP_features'					=> 'Особенности', 	//Features
'SHOP_THEME_GROUP_display'					=> 'Дисплей', 	//Display
'SHOP_THEME_GROUP_logo'						=> 'Логотип', 	//Logo
'SHOP_THEME_GROUP_favicons'					=> 'Фавиконок', 	//Favicons
'SHOP_THEME_GROUP_footer'					=> 'Нижний колонтитул', 	//Footer
'SHOP_THEME_GROUP_header'					=> 'Заголовок', 	//Header
'SHOP_THEME_GROUP_contact'					=> 'Контакты', 	//Contact
'SHOP_THEME_GROUP_googleanalytics'				=> 'Аналитика Google', 	//Google Analytics
'SHOP_THEME_GROUP_googlets'					=> 'Надежных Магазинах Гугл', 	//Google Trusted Stores
'SHOP_THEME_GROUP_background'					=> 'Фон-изображения', 	//Background-image
'SHOP_THEME_GROUP_econda'					=> 'econda интернет-магазин контроллинга', 	//econda Web Shop Controlling
'SHOP_THEME_GROUP_emails'					=> 'Электронной Почты', 	//E-Mails
'SHOP_THEME_sIconsize'						=> 'Размер значков (ширина*высота)', 	//Icon size (width*height)
'HELP_SHOP_THEME_sIconsize'					=> 'Иконки наименьшей цены товара. Они используются: <br><ul><li>в корзину.</li><li>если продукты представлены в правом меню (например, в <span class="filename_filepath_or_italic">TOP магазина</span> и <span class="filename_filepath_or_italic">поторговаться</span>).</li></ul>Для избежания проблем проектирования вызвана слишком большие значки изменяются. Введите максимальный размер для значков здесь.', 	//Icons are the smallest pictures of a product. They are used: <br><ul><li>in the shopping cart.</li><li>if products are shown in the right menu (e.g. in <span class="filename_filepath_or_italic">TOP of the Shop</span> and <span class="filename_filepath_or_italic">Bargain</span>).</li></ul>For avoiding design issues caused by too big icons the icons are resized. Enter the maximum size for icons here.
'SHOP_THEME_sThumbnailsize'					=> 'Эскиз Размер (ширина*высота)', 	//Thumbnail size (width*height)
'HELP_SHOP_THEME_sThumbnailsize'				=> 'Миниатюры-это небольшие изображения продукта. Они используются:<br><ul><li>в списках товаров.</li><li>в акции отображается в середине первой страницы, электронная. г. <span class="filename_filepath_or_italic">Только что прибыл!</span>.</li></ul>Для избежания проблем проектирования, вызванная слишком большой эскизы эскизы изменяются. Введите максимальный размер для миниатюры здесь.', 	//Thumbnails are small product pictures. They are used:<br><ul><li>in product lists.</li><li>in promotions displayed in the middle of the front page, e. g. <span class="filename_filepath_or_italic">Just arrived!</span>.</li></ul>For avoiding design issues caused by too big thumbnails the thumbnails are resized. Enter the maximum size for thumbnails here.
'SHOP_THEME_sZoomImageSize'					=> 'Увеличения размер изображения (ширина*высота)', 	//Zoom picture size (width*height)
'SHOP_THEME_sCatThumbnailsize'					=> 'Категория размер изображения (ширина*высота)', 	//Category picture size (width*height)
'HELP_SHOP_THEME_sCatThumbnailsize'				=> 'В представлении по категориям, картинки из выбранной категории отображается в определенном размере.', 	//In category view, the picture of the selected category is displayed in the defined size.
'SHOP_THEME_aDetailImageSizes'					=> 'Изображение Размер продукта (ширина*высота)', 	//Product picture size (width*height)
'SHOP_THEME_sManufacturerIconsize'				=> 'Производителя/Размер логотип бренда', 	//Manufacturer's/brand logo size
'HELP_SHOP_THEME_sManufacturerIconsize'				=> 'Логотип производителя/бренда показана на стартовую страницу в слайдер производителя.', 	//Manufacturer's/brand logo is shown on start page in manufacturer's slider.
'SHOP_THEME_sCatIconsize'					=> 'Размер изображения подкатегории (ширина*высота)', 	//Size of a subcategory's picture (width*height)
'HELP_SHOP_THEME_sCatIconsize'					=> 'Учитывая категорию, в категории картинки подкатегорий отображаются в определенном размере.', 	//In category view, the category pictures of subcategories are displayed in the defined size.
'SHOP_THEME_sCatPromotionsize'					=> 'Категория Размер изображение для продвижения в поле (ширина*высота)', 	//Category picture size for promotion on startpage (width*height)
'HELP_SHOP_THEME_sCatPromotionsize'				=> 'Продвижения категории на начальную страницу должен специальный Размер для категории картинки. Определить размер этих фотографий здесь.', 	//Category promotion on start page needs special size for category pictures. Define size of those pictures here.
'SHOP_THEME_blFooterShowHelp'					=> 'Помощь ссылка', 	//Use help link
'SHOP_THEME_blFooterShowLinks'					=> 'Используйте ссылки на ссылку', 	//Use Links link
'SHOP_THEME_blFooterShowGuestbook'				=> 'С помощью ссылки Гостевая книга', 	//Use guestbook link
'SHOP_THEME_blFooterShowNewsletter'				=> 'Используйте ссылку на бюллетень', 	//Use newsletter link
'SHOP_THEME_blFooterShowNewsletterForm'				=> 'Используйте форму бюллетеня', 	//Use newsletter form
'SHOP_THEME_blFooterShowNews'					=> 'Использовать ссылку новости', 	//Use news link
'SHOP_THEME_bl_showGiftWrapping'				=> 'Использовать подарочную упаковку', 	//Use gift wrapping
'SHOP_THEME_bl_showVouchers'					=> 'Использовать ваучеры', 	//Use vouchers
'SHOP_THEME_bl_showWishlist'					=> 'Использование реестра подарок', 	//Use gift registry
'SHOP_THEME_bl_showCompareList'					=> 'Используйте список сравнения', 	//Use compare list
'SHOP_THEME_bl_showListmania'					=> 'Использовать рестмалния', 	//Use listmania
'SHOP_THEME_blShowBirthdayFields'				=> 'Отображение поля ввода для даты рождения, когда пользователи вводят свои личные данные', 	//Display input fields for date of birth when users enter their personal data
'SHOP_THEME_iTopNaviCatCount'					=> 'Количество категорий, которые отображаются в верхней части', 	//Amount of categories that is displayed at top
'SHOP_THEME_blShowFinalStep'					=> 'Показать подтверждение заказа после того как заказ законченный (5-й шаг в оформлении заказа)', 	//Show order confirmation after order is finished (5th Step in Checkout)
'SHOP_THEME_iNewBasketItemMessage'				=> 'Выберите действие, когда товар добавляется в корзину', 	//Select action when product is added to cart
'HELP_SHOP_THEME_iNewBasketItemMessage'				=> 'Когда клиент добавляет товар в корзину, магазин и комбинации могут вести себя по-разному. Создать то, что должно произойти, чтобы дать правильную обратную связь с заказчиком.', 	//When customer adds products to cart, OXID eShop can behave differently. Set up what shall happen to give proper feedback to customer.
'SHOP_THEME_iNewBasketItemMessage_0'				=> 'Никто', 	//None
'SHOP_THEME_iNewBasketItemMessage_1'				=> 'Сообщение на дисплее', 	//Display message
'SHOP_THEME_iNewBasketItemMessage_2'				=> 'Открыть всплывающее окно', 	//Open popup
'SHOP_THEME_iNewBasketItemMessage_3'				=> 'Открыть корзину', 	//Open basket
'SHOP_THEME_blShowListDisplayType'				=> 'Отображать список товаров селектор типа', 	//Display product list type selector
'HELP_SHOP_THEME_blShowListDisplayType'				=> 'Решите, если посетитель вашего магазина сможет выбрать тип списка продуктов в магазин. Если эта опция не активирована, ваши посетители будут видеть в списках отображается, как вы скорректированный в раскрывающемся поле "Тип списка товаров по умолчанию".', 	//Decide if the visitor of your store can select the type of the product list in store front. If this options is not activated, your visitors will see the lists displayed like you adjusted in the drop box "Default product list type".
'SHOP_THEME_sDefaultListDisplayType'				=> 'Введите список продуктов по умолчанию', 	//Default product list type
'SHOP_THEME_sDefaultListDisplayType_grid'			=> 'Сетки', 	//Grid
'SHOP_THEME_sDefaultListDisplayType_line'			=> 'Список', 	//List
'SHOP_THEME_sDefaultListDisplayType_infogrid'			=> 'Двойной сетки', 	//Double grid
'SHOP_THEME_sStartPageListDisplayType'				=> 'Тип списка товаров на странице', 	//Product list type on Start page
'SHOP_THEME_sStartPageListDisplayType_grid'			=> 'Сетки', 	//Grid
'SHOP_THEME_sStartPageListDisplayType_line'			=> 'Список', 	//List
'SHOP_THEME_sStartPageListDisplayType_infogrid'			=> 'Двойной сетки', 	//Double grid
'SHOP_THEME_aNrofCatArticlesInGrid'				=> 'Вид сетки: количество продуктов, которые могут быть показаны в списках товаров (страницы категории, результатов поиска)<br><br>Внимание: большое количество товаров на странице (выше 100) может привести к потере производительности!', 	//Grid view: Number of products which can be shown in a product lists (category pages, search results)<br><br>Attention: A large number of products per page (above 100) can cause performance loss!
'SHOP_THEME_aNrofCatArticles'					=> 'Количество продуктов, которые могут быть показаны в списках товаров (страницы категории, результатов поиска)<br><br>Внимание: большое количество товаров на странице (выше 100) может привести к потере производительности!', 	//Number of products which can be shown in a product lists (category pages, search results)<br><br>Attention: A large number of products per page (above 100) can cause performance loss!
'SHOP_THEME_sFacebookUrl'					=> 'Страница-URL-адрес Facebook', 	//Facebook Page-URL
'HELP_SHOP_THEME_sFacebookUrl'					=> 'Е. г.: https://www.facebook.com/oxidesales', 	//E.g.: https://www.facebook.com/oxidesales
'SHOP_THEME_sTwitterUrl'					=> 'Профиль-URL-адрес в Twitter', 	//Twitter Profile-URL
'HELP_SHOP_THEME_sTwitterUrl'					=> 'Е. г.: https://twitter.com/OXID_eSales', 	//E.g.: https://twitter.com/OXID_eSales
'SHOP_THEME_sBlogUrl'						=> 'Блог-URL-адрес', 	//Blog-URL
'HELP_SHOP_THEME_sBlogUrl'					=> 'Е. г.: http://blog.oxid-esales.com', 	//E.g.: http://blog.oxid-esales.com
'SHOP_THEME_sYouTubeUrl'					=> 'Канал-ссылку на YouTube', 	//YouTube Channel-URL
'HELP_SHOP_THEME_sYouTubeUrl'					=> 'Е. г.: https://www.youtube.com/user/oxidesales', 	//E.g.: https://www.youtube.com/user/oxidesales
'SHOP_THEME_sGooglePlusUrl'					=> 'Google+ страница-URL-адрес', 	//Google+ Page-URL
'HELP_SHOP_THEME_sGooglePlusUrl'				=> 'Е. г.: https://plus.google.com/114133952363540971062', 	//E.g.: https://plus.google.com/114133952363540971062
'SHOP_THEME_sGoogleMapsAddr'					=> 'Ваш почтовый адрес', 	//Your postal address
'HELP_SHOP_THEME_sGoogleMapsAddr'				=> 'Е. г.: Оксид Джек-де-Pierre АГ Bertoldstraße 48, 79098 Фрайбург', 	//E.g.: OXID eSales AG, Bertoldstraße 48, 79098 Freiburg
'SHOP_THEME_bl_showManufacturerSlider'				=> 'Показать производитель слайдер на главной странице', 	//Show manufacturer slider on Start page
'SHOP_THEME_blUseGAPageTracker'					=> 'Использовать Аналитику Google PageTracker', 	//Use Google Analytics PageTracker
'SHOP_THEME_blUseGAEcommerceTracking'				=> 'Используйте Google Analytics Отслеживание Электронной Коммерции', 	//Use Google Analytics Ecommerce Tracking
'HELP_SHOP_THEME_blUseGAEcommerceTracking'			=> 'Пожалуйста, имейте в виду, что этот параметр должен быть включен в вашем аккаунте Google Analytics и тоже. Инструкция: <a href="https://support.google.com/analytics/answer/1009612?hl=en&amp;ref_topic=1037061" target="_blank">Ссылка</a>', 	//Please keep in mind that this option needs to be enabled in your Google Analytics account, too. Manual: <a href="https://support.google.com/analytics/answer/1009612?hl=en&ref_topic=1037061" target="_blank">Link</a>
'SHOP_THEME_sGATrackingId'					=> 'Трекинг-код гугл аналитики', 	//Google Analytics Tracking-ID
'HELP_SHOP_THEME_sGATrackingId'					=> 'Е. г.: НА UA-ХХХХХХХХ-1', 	//E.g.: UA-XXXXXXXX-1
'SHOP_THEME_blGAAnonymizeIPs'					=> 'Анонимизировать IP-адреса', 	//Anonymize IP-Adresses
'SHOP_THEME_sLogoFile'						=> 'Именем логотипа', 	//Filename of logo
'HELP_SHOP_THEME_sLogoFile'					=> 'Это относительный путь <code>/выход/расход/имг/</code>.', 	//This is relative to the path <code>/out/flow/img/</code>.
'SHOP_THEME_sLogoWidth'						=> 'Ширина логотипа', 	//Width of header logo
'HELP_SHOP_THEME_sLogoWidth'					=> 'Укажите в качестве пиксельного значения.', 	//Specify in as a pixel value.
'SHOP_THEME_sLogoHeight'					=> 'Высота логотипа', 	//Height of header logo
'HELP_SHOP_THEME_sLogoHeight'					=> 'Укажите в качестве пиксельного значения.', 	//Specify in as a pixel value.
'SHOP_THEME_sEmailLogo'						=> 'Именем логотипа для заголовка сообщения', 	//Filename of logo for email header
'HELP_SHOP_THEME_sEmailLogo'					=> 'Это относительный путь <code>/выход/расход/имг/</code>.', 	//This is relative to the path <code>/out/flow/img/</code>.
'SHOP_THEME_sFaviconFile'					=> 'Фавикон именем', 	//Favicon filename
'HELP_SHOP_THEME_sFaviconFile'					=> 'Этот значок предназначен для отображения на вкладке браузера.<br>В общем, это файл ICO.<br>Это относительный путь <code>/выход/расход/имг/значки/</code>.', 	//This favicon is meant to be displayed in the browser's tab.<br>In general, this is an ico file.<br>This is relative to the path <code>/out/flow/img/favicons/</code>.
'SHOP_THEME_sFavicon16File'					=> 'Имя файла фавикон с 16*16 пикселов.', 	//Filename of the favicon with 16*16px.
'SHOP_THEME_sFavicon32File'					=> 'Имя файла фавикон с 32*32px.', 	//Filename of the favicon with 32*32px.
'SHOP_THEME_sFavicon48File'					=> 'Имя файла фавикон с 48*48px.', 	//Filename of the favicon with 48*48px.
'SHOP_THEME_sFavicon64File'					=> 'Имя файла фавикон с 64*64px.', 	//Filename of the favicon with 64*64px.
'SHOP_THEME_sFavicon128File'					=> 'Имя файла фавикон с 128*128px.', 	//Filename of the favicon with 128*128px.
'SHOP_THEME_sFavicon512File'					=> 'Имя файла фавикон с 512*512 пикс.', 	//Filename of the favicon with 512*512px.
'SHOP_THEME_sFaviconMSTileColor'				=> 'Цвет плитки для Windows 8 и Windows Мобильные закладки.', 	//Tile color for Windows 8/Windows Mobile bookmarks.
'HELP_SHOP_THEME_sFaviconMSTileColor'				=> 'Задается как шестнадцатеричное значение.<br>Е. г.: #D83434', 	//Specified as a hexadecimal value.<br>E.g.: #D83434
'SHOP_THEME_blUseBackground'					=> 'Показать фон-изображение', 	//Show background-image
'SHOP_THEME_sBackgroundColor'					=> 'Фон-цвет, магазин', 	//Background-color of shop
'HELP_SHOP_THEME_sBackgroundColor'				=> 'Задается как шестнадцатеричное значение.<br>Е. г.: #D83434', 	//Specified as a hexadecimal value.<br>E.g.: #D83434
'SHOP_THEME_sBackgroundPath'					=> 'Имя файла фонового изображения', 	//Filename of background-image
'HELP_SHOP_THEME_sBackgroundPath'				=> 'Это относительный путь <code>/выход/расход/имг/фоны/</code>.', 	//This is relative to the path <code>/out/flow/img/backgrounds/</code>.
'SHOP_THEME_sBackgroundRepeat'					=> 'Повтор фонового изображения?', 	//Repeat background-image?
'SHOP_THEME_sBackgroundRepeat_no-repeat'			=> 'Нет', 	//No
'SHOP_THEME_sBackgroundRepeat_repeat-x'				=> 'Да, горизонтальный', 	//Yes, horizontal
'SHOP_THEME_sBackgroundRepeat_repeat-y'				=> 'Да, вертикальная', 	//Yes, vertical
'SHOP_THEME_sBackgroundRepeat_repeat'				=> 'Да, по горизонтали и вертикали', 	//Yes, horizontal und vertical
'SHOP_THEME_sBackgroundPosHorizontal'				=> 'Горизонтальное положение фонового изображения', 	//Horizontal position of the background-image
'SHOP_THEME_sBackgroundPosHorizontal_left'			=> 'левый', 	//left
'SHOP_THEME_sBackgroundPosHorizontal_right'			=> 'право', 	//right
'SHOP_THEME_sBackgroundPosHorizontal_center'			=> 'центрированный', 	//centered
'SHOP_THEME_sBackgroundPosVertical'				=> 'Вертикальное положение фонового изображения', 	//Vertical position of the background-image
'SHOP_THEME_sBackgroundPosVertical_top'				=> 'топ', 	//top
'SHOP_THEME_sBackgroundPosVertical_bottom'			=> 'дно', 	//bottom
'SHOP_THEME_sBackgroundPosVertical_center'			=> 'центрированный', 	//centered
'SHOP_THEME_sBackgroundSize'					=> 'Фон-размер изображения', 	//Background-image size
'SHOP_THEME_sBackgroundSize_cover'				=> 'крышка (полная высота)', 	//cover (full height)
'SHOP_THEME_sBackgroundSize_contain'				=> 'крышка (полная Ширина)', 	//cover (full width)
'SHOP_THEME_sBackgroundSize_normal'				=> 'Сохранить исходный Размер', 	//Keep original size
'SHOP_THEME_blBackgroundAttachment'				=> 'Исправить фон при прокрутке?', 	//Fix background while scrolling?
'SHOP_THEME_blUseGoogleTS'					=> 'Используйте Google Надежных Магазинах', 	//Use Google Trusted Stores
'SHOP_THEME_sGoogleVendorId'					=> 'Магазин Google-ИД', 	//Google Store-ID
'HELP_SHOP_THEME_sGoogleVendorId'				=> 'Вы можете найти этот ID в надежных магазинах торгового dashboard.', 	//You can find this ID in your Trusted Stores Merchant Dashboard.
'SHOP_THEME_sGoogleShoppingAccountId'				=> 'Торговый счет-идентификатор Google (опционально)', 	//Google Shopping Account-ID (optional)
'HELP_SHOP_THEME_sGoogleShoppingAccountId'			=> 'Обеспечить это поле только если вы представите кормов для Google покупках.<br><br>Идентификатор аккаунт в Merchant Center для Google. Это значение должно совпадать с ID учетной записи вы используете, чтобы представить свой <a href="https://support.google.com/merchants/answer/188494#US" target="_blank">продукт, подача данных в Google покупки</a> через Гугл Мерчант центр. Если у вас есть аккаунт СМА, использовать субсчета идентификатор, связанный с кормовой продукт.', 	//Provide this field only if you submit feeds for Google Shopping.<br><br>Account ID from Google Merchant Center. This value should match the account ID you use to submit your <a href="https://support.google.com/merchants/answer/188494#US" target="_blank">product data feed to Google Shopping</a> through Google Merchant center. If you have a MCA account, use the subaccount ID associated with that product feed.
'SHOP_THEME_sPageLanguage'					=> 'Язык ваш магазин в ISO', 	//Language of your Shop in ISO
'HELP_SHOP_THEME_sPageLanguage'					=> 'Язык должен быть в формате &lt;язык&gt;_&lt;страна&gt;<br><br>&lt;Язык&gt;-это двухбуквенный код языка, определенных в стандарте ISO 639-1, и &lt;страна&gt; - это двухбуквенный код, определенный в стандарте ISO 3166-1 Альфа-2. Как правило, &lt;страна&gt; должны быть все с большой буквы, и &lt;язык&gt; должны быть в Нижнем регистре. например: en_us, en_GB, en_AU, называться fr_fr, в ru_RU, или ja_JP.', 	//The locale should be in the format of &lt;language&gt;_&lt;country&gt;<br><br>&lt;Language&gt; is a two-letter language code defined in ISO 639-1, and &lt;country&gt; is a two-letter country code defined in ISO 3166-1 alpha-2. Usually &lt;country&gt; should be all capitalized, and &lt;language&gt; should be in lowercase. e.g. en_US, en_GB, en_AU, fr_FR, de_DE, or ja_JP.
'SHOP_THEME_sShoppingCountry'					=> 'Магазины-ленту гугла Страна (необязательно)', 	//Google Shopping-Feed Country (optional)
'HELP_SHOP_THEME_sShoppingCountry'				=> 'Обеспечить это поле только если вы представите кормов для Google покупках.<br><br>Страна аккаунта из Google покупок. Это значение должно совпадать со счета страны, который вы используете для отправки ваших <a href="https://support.google.com/merchants/answer/188494#US" target="_blank">фидов товаров в Google покупках</a>.<br><br>Значение параметра страны должны быть <a href="http://en.wikipedia.org/wiki/ISO_3166-1_alpha-2" target="_blank">двухбуквенный ISO 3166 код страны</a>.<br><br>Например, ценности могут быть США, Великобритании, Австралии, Франции, де, ДП.', 	//Provide this field only if you submit feeds for Google Shopping.<br><br>Account country from Google Shopping. This value should match the account country you use to submit your <a href="https://support.google.com/merchants/answer/188494#US" target="_blank">product data feed to Google Shopping</a>.<br><br>The value of the country parameter should be a <a href="http://en.wikipedia.org/wiki/ISO_3166-1_alpha-2" target="_blank">two-letter ISO 3166 country code</a>.<br><br>For example, values could be US, GB, AU, FR, DE, JP.
'SHOP_THEME_sShoppingLanguage'					=> 'Магазины-ленту гугла в sprache (опционально)', 	//Google Shopping-Feed Sprache (optional)
'HELP_SHOP_THEME_sShoppingLanguage'				=> 'Обеспечить это поле только если вы представите кормов для Google покупках.<br><br>Язык аккаунта из Google покупок. Это значение должно соответствовать учетной записи язык, который вы используете, чтобы представить свой <a href="https://support.google.com/merchants/answer/188494#US" target="_blank">продукт, подача данных в Google покупки</a>.<br><br>Значение языка параметра должно быть <a href="http://en.wikipedia.org/wiki/ISO_639-1" target="_blank">двухбуквенный ISO 639-1 код языка</a>.<br><br>Например, ценности могут быть английском, французском, немецком, Дж.', 	//Provide this field only if you submit feeds for Google Shopping.<br><br>Account language from Google Shopping. This value should match the account language you use to submit your <a href="https://support.google.com/merchants/answer/188494#US" target="_blank">product data feed to Google Shopping</a>.<br><br>The value of the language parameter should be a <a href="http://en.wikipedia.org/wiki/ISO_639-1" target="_blank">two-letter ISO 639-1 language code</a>.<br><br>For example, values could be en, fr, de, ja.
'SHOP_THEME_sShippingDaysOnStock'				=> 'Количество дней до доставки заказа, все статьи в наличии.', 	//Amount of days till shipping of an order that has all articles in stock.
'HELP_SHOP_THEME_sShippingDaysOnStock'				=> 'Ориентировочная Дата, на которую вы отправляете заказ; это отличается от расчетной даты доставки.<br><br>Если заказ содержит несколько элементов, выберите последний ориентировочная Дата отгрузки.<br><br>Если вы сообщение к вашим клиентам целый ряд дней, пожалуйста, включите позднее конца диапазона. (например, 7 дней если ваш выбор доставка 5-7 дней).<br><br>Дата, указанная здесь, будет предоставлена Заказчику по электронной почте.<br><br>Клиент получит обследования после покупки после Расчетная Дата отгрузки прошло.', 	//The estimated date on which you will ship the order; this is different from the estimated delivery date.<br><br>If the order contains multiple items, select the latest estimated ship date.<br><br>If you message to your customers a range of days, please include the later end of the range. (e.g., 7 days if your shipping range is 5-7 days).<br><br>The date provided here will be provided to the customer via email.<br><br>The customer will receive a post purchase survey after the Estimated Ship Date has passed.
'SHOP_THEME_sShippingDaysNotOnStock'				=> 'Количество дней до доставки заказа, <b>не</b> все статьи в наличии.', 	//Amount of days till shipping of an order that has <b>not</b> all articles in stock.
'HELP_SHOP_THEME_sShippingDaysNotOnStock'			=> 'Ориентировочная Дата, на которую вы отправляете заказ; это отличается от расчетной даты доставки.<br><br>Если заказ содержит несколько элементов, выберите последний ориентировочная Дата отгрузки.<br><br>Если вы сообщение к вашим клиентам целый ряд дней, пожалуйста, включите позднее конца диапазона. (например, 7 дней если ваш выбор доставка 5-7 дней).<br><br>Дата, указанная здесь, будет предоставлена Заказчику по электронной почте.<br><br>Клиент получит обследования после покупки после Расчетная Дата отгрузки прошло.', 	//The estimated date on which you will ship the order; this is different from the estimated delivery date.<br><br>If the order contains multiple items, select the latest estimated ship date.<br><br>If you message to your customers a range of days, please include the later end of the range. (e.g., 7 days if your shipping range is 5-7 days).<br><br>The date provided here will be provided to the customer via email.<br><br>The customer will receive a post purchase survey after the Estimated Ship Date has passed.
'SHOP_THEME_sDeliveryDaysOnStock'				=> 'Количество дней до доставки заказа, все статьи в наличии.', 	//Amount of days till delivery of an order that has all articles in stock.
'HELP_SHOP_THEME_sDeliveryDaysOnStock'				=> 'Ориентировочная Дата, на которую вы ожидаете доставки заказа клиенту. Если заказ содержит несколько элементов, выберите самую позднюю дату доставки. Если вы сообщение диапазон дней, пожалуйста, включите позднее конца диапазона. (например, 7 дней, если ваш диапазон 5-7 дней).', 	//The estimated date on which you expect delivery of the order to the customer. If the order contains multiple items, select the latest delivery date. If you message a range of days, please include the later end of the range. (e.g., 7 days if your range is 5-7 days).
'SHOP_THEME_sDeliveryDaysNotOnStock'				=> 'Количество дней до доставки заказа, что <b>не</b> все статьи в наличии.', 	//Amount of days till delivery of an order that has <b>not</b> all articles in stock.
'HELP_SHOP_THEME_sDeliveryDaysNotOnStock'			=> 'Ориентировочная Дата, на которую вы ожидаете доставки заказа клиенту. Если заказ содержит несколько элементов, выберите самую позднюю дату доставки. Если вы сообщение диапазон дней, пожалуйста, включите позднее конца диапазона. (например, 7 дней, если ваш диапазон 5-7 дней).', 	//The estimated date on which you expect delivery of the order to the customer. If the order contains multiple items, select the latest delivery date. If you message a range of days, please include the later end of the range. (e.g., 7 days if your range is 5-7 days).
'SHOP_THEME_blSliderShowImageCaption'				=> 'Активировать субтитры для слайдера на главной странице', 	//Activate captions for slider on home page
'HELP_SHOP_THEME_blSliderShowImageCaption'			=> 'Надпись видна, когда активный слайд имеет присвоенный продукту.', 	//A caption is visible, when the active slide has an assigned product.
'SHOP_THEME_sEcondaAccountId'					=> 'econda-ИД', 	//econda-ID
'HELP_SHOP_THEME_sEcondaAccountId'				=> 'Пожалуйста, введите ваш ID econda.<br>Формат: ХХХХХХХХ-ХХХХХХХХ-ХХХХ-ХХХХ-ХХХХ-ХХХХХХХХХХХХ-Х.<br>Пожалуйста, имейте в виду, чтобы активировать econda-магазине контроллинга в ваш магазин.', 	//Please enter your econda ID.<br>Format: XXXXXXXX-XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX-X.<br>Please keep in mind to activate the econda Webshop Controlling in your shop.
'SHOP_THEME_blEcondaRecommendationsStart'			=> 'Показать рекомендаций на главной странице', 	//Show recommendations on home page
'SHOP_THEME_sEcondaWidgetIdStart'				=> 'Рекомендация-виджет-идентификатор фюр сайт удобнее', 	//Recommendation-Widget-ID für Startseite
'SHOP_THEME_blEcondaRecommendationsList'			=> 'Показать рекомендаций в списки', 	//Show recommendations in listings
'SHOP_THEME_sEcondaWidgetIdList'				=> 'Рекомендация-виджет-идентификатор фюр Listenansicht', 	//Recommendation-Widget-ID für Listenansicht
'SHOP_THEME_blEcondaRecommendationsDetails'			=> 'Показать рекомендации на странице подробности', 	//Show recommendations on details page
'SHOP_THEME_sEcondaWidgetIdDetails'				=> 'Рекомендация-виджет-идентификатор фюр Detailseite', 	//Recommendation-Widget-ID für Detailseite
'SHOP_THEME_blEcondaRecommendationsBasket'			=> 'Показать рекомендации в корзину', 	//Show recommendations in basket
'SHOP_THEME_sEcondaWidgetIdBasket'				=> 'Рекомендация-виджет-идентификатор фюр Warenkorb', 	//Recommendation-Widget-ID für Warenkorb
'SHOP_THEME_blFullwidthLayout'					=> 'Активировать полную с макета', 	//Activate full with layout
'SHOP_THEME_blEmailsShowProductPictures'			=> 'Показать изображения продукта по электронной почте', 	//Show product pictures in emails
''=>'' );
